### Comic 1 
POST  http://localhost:4000/comics
Content-Type: application/json

{
    "name": "SPIDERMAN",
    "description": "Who will be the new Phoenix?! The planet-spraying cosmic bird known as the Phoenix Force has returned, and the Avengers are summoned for a global battle for ultimate power! In the distant past of the year one million B.C., the only crime of a young woman was to be born with red hair, and her fate will change the history of mankind forever!",
    "price": 5,
    "image":"https://tap-multimedia-1172.nyc3.digitaloceanspaces.com/productimage/44241/9786076360910.jpg",
    "rating": 4,
    "pageCount": 180,
    "language":"en-es"
}